# Generated by Django 6.1 on 2026-08-25 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='usuarios.especialista'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='horariogerado',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agendamentos.agenda'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='horario_gerado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='agendamentos.horariogerado'),
        ),
    ]
