# Generated by Django 6.1 on 2026-08-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agenda_ativo_consulta_ativo_especialidade_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariogerado',
            name='data',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
