# Generated by Django 6.1 on 2026-08-27

from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='horariogerado',
            constraint=models.CheckConstraint(
                condition=Q(horario_fim__gt=F('horario_inicio')),
                name='horario_fim_posterior_inicio',
            ),
        ),
        migrations.AddConstraint(
            model_name='horariogerado',
            constraint=models.UniqueConstraint(
                fields=('agenda', 'data', 'horario_inicio'),
                name='horario_unico_por_agenda_data_inicio',
            ),
        ),
    ]
