# Generated by Django 6.1 on 2026-08-27

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_horariogerado_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='horariogerado',
            name='horario_unico_por_agenda_data_inicio',
        ),
        migrations.AddConstraint(
            model_name='horariogerado',
            constraint=models.UniqueConstraint(
                condition=Q(ativo=True),
                fields=('agenda', 'data', 'horario_inicio'),
                name='horario_unico_por_agenda_data_inicio',
            ),
        ),
    ]
