# Generated by Django 6.1 on 2026-08-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_horariogerado_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('ESPECIALISTA', 'Especialista'), ('PACIENTE', 'Paciente'), ('INTERNO', 'Interno')], max_length=15, null=True),
        ),
    ]
