# Generated by Django 6.1 on 2026-08-27 20:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_horario_unique_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='especialidade',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome_especialidade'), name='especialidade_nome_unico_case_insensitive'),
        ),
    ]
